spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      dev:
        - db-dev
    include:
      - db
      - jwt
      - log
      - server
      - swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher