cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: kkini
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB